#
# Makefile for Chapter 02
#
# Type  make    to compile all the programs
# in the chapter 
#

all: who1 who2 cp1

clean:
	rm -f who1 who2 cp1

who1: who1.c 
	cc -o who1 who1.c 

who2: who2.c 
	cc -o who2 who2.c 

cp1: cp1.c
	cc -o cp1 cp1.c
